# Generated by Django 6.1.1 on 2026-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=30)),
                ('service', models.CharField(choices=[('Assignment', 'Assignment'), ('Essay', 'Essay'), ('Research Project', 'Research Project'), ('Dissertation', 'Dissertation'), ('IT Project', 'IT Project'), ('Presentation', 'Presentation'), ('Other', 'Other')], max_length=50)),
                ('project_title', models.CharField(max_length=200)),
                ('requirements', models.TextField()),
                ('deadline', models.DateField()),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
