# Generated by Django 6.1.1 on 2026-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Assignment', 'Assignment'), ('Essay', 'Essay'), ('Research Project', 'Research Project'), ('Dissertation', 'Dissertation'), ('IT Project', 'IT Project'), ('Presentation', 'Presentation'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='samples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
